---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml



    - name: "install python for Ansible."
      apt:
        name: ["python"]
        state: latest
        update_cache: yes



  roles:
    # Your code here
    - configure-server
